/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "RCC_interface.h"
#include "BIT_MATH.h"
#include "GPIO_private.h"
#include "STD_TYPES.h"
#include "NVIC_interface.h"
#include "DMA_interface.h"
void _delay_ms(u32 ms);


void SingleISR();

static u16 i=0;
int main(void)
{
	RCC_voidSysClkInit();
	RCC_voidEnablePerClk(RCC_AHB1,0);
	RCC_voidEnablePerClk(RCC_AHB1,21); // enable rcc for DMA1
	u32 source1DMA[1000] = {0};
	u32 destination1DMA[1000];

	u32 source[1000] = {0};
	u32 Destination[1000];
	DMA_voidStart(source1DMA,destination1DMA,1000);

	for(i = 0;i<1000;i++){
		Destination[i] = source[i];
	}




	/*
	 A5 output	push pull
	 C13 input pull up

	 */
	//NVIC_voidInit();
	/* NVIC EXT1 Enable Interrupt peripheral */
	//NVIC_voidSetInterruptEnable(6);
	/* EXTI 0  GRP 2 sub 2*/
	//NVIC_voidSetIntPriotity(6,0b1010);

	//NVIC_voidClrPending(6);
	SET_bit(GPIOA_MODE,0);
	CLR_bit(GPIOA_MODE,1);
	SET_bit(GPIOA_ODR,0);
	STK_voidSingleInterval(1,SingleISR);
	//A5 LED || C13 Button

	/*
	SET_bit(GPIOA_ODR,0);
	STK_voidBusyWait(1000000);
	CLR_bit(GPIOA_ODR,0);
	STK_voidBusyWait(1000000);
	*/
    /* Loop forever */
	while(1)
	{

		/*
		SET_bit(GPIOA_ODR,0);
		_delay_ms(1000);
		CLR_bit(GPIOA_ODR,0);
		_delay_ms(1000);*/

	}
}


void _delay_ms(u32 ms)
{
	for (u32 i = 0; i < 500 * ms; i++)
	{
		i++;
	}
}



void EXTI0_IRQHandler(){

	/* Clear The Flag */

	//SET_bit(GPIOA_ODR,4);
}



void SingleISR(){
	CLR_bit(GPIOA_ODR,0);
}

