/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "RCC_interface.h"
#include "BIT_MATH.h"
#include "GPIO_private.h"
#include "STD_TYPES.h"
#include "NVIC_interface.h"
#include "DMA_interface.h"

#include "FreeRTOS.h"
#include "FreeRTOSConfig.h"
#include "task.h"
#include "semphr.h"

u8 flag = 0;
void _delay_ms(u32 ms);


void SingleISR();


void Led1(){
	SET_bit(GPIOA_ODR,0);
}

void vRedTask(void * pvParameters){

	for( ;; ){
		vTaskDelay(200);
		if(flag){
		SET_bit(GPIOA_ODR,0);
		flag = 0;
		}
		else{
		CLR_bit(GPIOA_ODR,0);
		}
	}
}

void vGreenTask(void * pvParameters){

	for( ;; ){
		vTaskDelay(100);
		if(GET_bit(GPIOC_IDR,12) == 1){
			flag = 1;
		}



	}
}


int main(void)
{
	RCC_voidSysClkInit();
	RCC_voidEnablePerClk(RCC_AHB1,0);

	SET_bit(GPIOA_MODE,0);
	CLR_bit(GPIOA_MODE,1);
	CLR_bit(GPIOA_MODE,2);
	CLR_bit(GPIOA_MODE,3);

	CLR_bit(GPIOA_MODE,26);
	CLR_bit(GPIOA_MODE,37);

	//SET_bit(GPIOA_PUPDR,2);
	//CLR_bit(GPIOA_PUPDR,3);

	TaskHandle_t	xHandleGreenLed = NULL;
	TaskHandle_t	xHandleRedLed = NULL;

	xTaskCreate(vRedTask,"Red LED Task",85,NULL,2,&xHandleRedLed );
	xTaskCreate(vGreenTask,"Green LED Task",85,NULL,1,&xHandleGreenLed );


	/*
	RCC_voidEnablePerClk(RCC_AHB1,21); // enable rcc for DMA1
	u32 source1DMA[1000] = {0};
	u32 destination1DMA[1000];


	u32 source[1000] = {0};
	u32 Destination[1000];
	DMA_voidStart(source1DMA,destination1DMA,1000);

	for(i = 0;i<1000;i++){
		Destination[i] = source[i];
	}

*/


	/*
	 A5 output	push pull
	 C13 input pull up

	 */
	//NVIC_voidInit();
	/* NVIC EXT1 Enable Interrupt peripheral */
	//NVIC_voidSetInterruptEnable(6);
	/* EXTI 0  GRP 2 sub 2*/
	//NVIC_voidSetIntPriotity(6,0b1010);

	//NVIC_voidClrPending(6);
	//SET_bit(GPIOA_MODE,0);
	//CLR_bit(GPIOA_MODE,1);
	//RTO_voidCreateTask(0, 1000, Led1);
	//SET_bit(GPIOA_ODR,0);
	//STK_voidSingleInterval(1,SingleISR);
	//A5 LED || C13 Button

	/*
	SET_bit(GPIOA_ODR,0);
	STK_voidBusyWait(1000000);
	CLR_bit(GPIOA_ODR,0);
	STK_voidBusyWait(1000000);
	*/
    /* Loop forever */
	vTaskStartScheduler();
	while(1)
	{

		/*
		SET_bit(GPIOA_ODR,0);
		_delay_ms(1000);
		CLR_bit(GPIOA_ODR,0);
		_delay_ms(1000);*/

	}
}


void _delay_ms(u32 ms)
{
	for (u32 i = 0; i < 500 * ms; i++)
	{
		i++;
	}
}



void EXTI0_IRQHandler(){

	/* Clear The Flag */

	//SET_bit(GPIOA_ODR,4);
}



void SingleISR(){
	CLR_bit(GPIOA_ODR,0);
}

